### ISSUE TITLE
How can I install it on localhost? 

### ISSUE THREAD

**Issue by GildedHonour** [wennycooper/wsProject#1]
How can I install it on localhost? What do I need to change to not depend on your server at all?

**Comment by GildedHonour** [comment]
And when it's installed, how can I connect to it and send a message from android device (one browser and one android device)? The android device already have AppRtc app installed in it.

**Comment by wennycooper** [comment]
"wsProject" contains a webrtc signaling server (wsServer.js) and a html5 webrtc client (wsClient.html). 
To install the wsProject,, plz read https://github.com/wennycooper/wsProject/blob/master/README.md
To change the client code to use your own signaling server, you can modify the code "wsClient.html" in line:13.

"webrtcClient" is a  webrtc client on Android. To change the code to use your own signaling server, you can modify the line:29 in https://github.com/wennycooper/webrtcClient/blob/master/src/com/kkuei/demo/webrtc/WebrtcChannel.java
